// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzgMQzjrR_ZKqa7O7MwPVRqi_zAzM64Gw',
    appId: '1:498947750576:web:7482f1d557d8b2eeb71975',
    messagingSenderId: '498947750576',
    projectId: 'dream-job-e6703',
    authDomain: 'dream-job-e6703.firebaseapp.com',
    storageBucket: 'dream-job-e6703.firebasestorage.app',
    measurementId: 'G-C3NRQSTJSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4AE5E0VHy2uYX1-tvaZ818XOcp8Wm77I',
    appId: '1:498947750576:android:c24d619e1853d3c6b71975',
    messagingSenderId: '498947750576',
    projectId: 'dream-job-e6703',
    storageBucket: 'dream-job-e6703.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3flLGkaGYcRzKfkHv3mz_pCLr3wiYxPI',
    appId: '1:498947750576:ios:8dbd61c2c480be2eb71975',
    messagingSenderId: '498947750576',
    projectId: 'dream-job-e6703',
    storageBucket: 'dream-job-e6703.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzgMQzjrR_ZKqa7O7MwPVRqi_zAzM64Gw',
    appId: '1:498947750576:web:7482f1d557d8b2eeb71975',
    messagingSenderId: '498947750576',
    projectId: 'dream-job-e6703',
    authDomain: 'dream-job-e6703.firebaseapp.com',
    storageBucket: 'dream-job-e6703.firebasestorage.app',
    measurementId: 'G-C3NRQSTJSJ',
  );
}
